### ISSUE TITLE
Less or Sass's shortcut variables reflect to css attributes

### ISSUE THREAD

**Issue by fontEndEasy** [fontEndEasy/socket.io#4]
```less
@b: border;
@bl: border-left;
@br: border-right;
@bt: border-top;
@bb: border-bottom;
@bbc: border-bottom-color;
@bblr: border-bottom-left-radius;
@bbrr: border-bottom-right-radius;
@bbs: border-bottom-style;
@bbw: border-bottom-width;
@bts: border-top-style;
@btw: border-top-width;
@btc: border-top-color;
@btlr: border-top-left-radius;
@btrr: border-top-right-radius;
@blc: border-left-color;
@bls: border-left-style;
@blw: border-left-width;
@brc: border-left-color;
@brs: border-left-style;
@brw: border-left-width;
@bi: border-image;
@bra: border-radius;
@um: user-modify;
@bz: box-sizing;

@ba: box-align;
@bdb: box-decoration-break;
@bdr: box-direction;
@bf: box-flex;
@bfg: box-flex-group;
@bl: box-lines;
@bog: box-ordinal-group;
@bo: box-orient;
@bp: box-pack;
@br: box-reflect;


@cc: column-count;
@cf: column-fill;
@cg: column-gap;
@crc: column-rule-color;
@crs: column-rule-style;
@crw: column-rule-width;
@cs: column-span;
@cw: column-width;
@ct: content;
@ci: counter-increment;
@cr: cursor;
@d: direction;

@m: margin;
@ml: margin-left;
@mr: margin-right;
@mt: margin-top;
@mb: margin-bottom;
@p: padding;
@pl: padding-left;
@pr: padding-right;
@pt: padding-top;
@pb: padding-bottom;

@lst: list-style-type;
@lsi: list-style-image;
@lsp: list-style-position;
@pe: pointer-events;


@bs: box-shadow;
@a: animate;
@an: animate-name;
@ad: animate-delay;
@adi: animate-direction;
@adu: animate-duration;
@afm: animate-fill-mode;
@atf: animate-timing-function;
@bg: background;
@bc: background-color;
@ba: background-attachment;
@bbm: background-blend-mode;
@bcp: background-clip;
@bgi: background-image;
@bgo: background-origin;
@bpx: background-position-x;
@bpy: background-position-y;
@bgr: background-repeat;
@brx: background-repeat-x;
@bry: background-repeat-y;
@bgs: background-size;

@ts: transform;
@ty: transform-type;
@tso: transform-origin;
@tss: transform-style;
@trs: transition;
@trsd: transition-delay;
@trsd: transition-duration;
@trsp: transition-property;
@trsf: transition-timing-function;
@tox: transform-origin-x;
@toy: transform-origin-y;
@ps: perspective;
@pso: perspective-origin;



@fz: font-size;
@ff: font-family;
@lh: line-height;
@fw: font-weight;
@fv: font-variant;
@fy: font-style;
@fsa: font-size-adjust;
@td: text-decoration;
@tdc: text-decoration-color;
@tdl: text-decoration-line;
@tskip: text-decoration-skip;
@tds: text-decoration-style;
@tj: text-justify;
@tori: text-orientation;
@wb: word-break;
@ws: word-spacing;
@ww: word-wrap;
@wm: writing-mode;
@z: z-index;
@zm: zoom;

@tup: text-underline-postion;
@ts: text-shadow;
@to: text-overflow;
@va: vertical-align;
@ta: text-align;
@ti: text-indent;
@tauto: text-autospace;
@tt: text-transform;
@ls: letter-spacing;
@fs: font-stretch;
@thc: tap-highlight-color;
@tfc: text-fill-color;
@tsc: text-stroke-color;
@tsw: text-stroke-width;
@tor: text-orientation;

@g: grid;
@gac: grid-auto-columns;
@gaf: grid-auto-flow;
@gar: grid-auto-rows;
@gce: grid-column-end;
@gcg: grid-column-gap;
@gcs: grid-column-start;
@gre: grid-row-end;
@grs: grid-row-start;
@grg: grid-row-gap;
@gta: grid-template-areas;
@gtc: grid-template-columns;
@gtr: grid-template-rows;



@o: opacity;



@h: height;
@w: width;
@maw: max-width;
@miw: min-width;
@mah: max-height;
@mih: min-height;

@p: position;
@fl: flex;
@fd: flex-direction;
@fb: flex-basis;
@fg: flex-grow;
@fs: flex-shrink;
@fw: flex-wrap;
@jc: justify-content;
@ji: justify-items;
@js: justify-self;
@o: order;
@ac: align-content;
@ai: align-items;
@as: align-self;


@oc: outline-color;
@oo: outline-offset;
@ot: outline-style;
@ow: outline-width;
@oa: outline-anchor;
@ow: outline-wrap;
@ox: overflow-x;
@of: overflow;
@oy: overflow-y;

@f: float;
@l: left;
@r: right;
@c: clear;
```

 ## How to Usage it:
> Make sure you use the less.
> Then you can use the variables above like this:

```less
 selector{
          @{bc}: red;
          @{f}: left;
          @{w}: 200px;
          @{h}: 200px;
          @{ts}: rotate(45deg)
          @{an}: anim;
          @{ad}: .5s;
          @{adi}: alternate;
          @{adu}: .5ms;
          @{afm}: forwards;
          @{atf}: ease / cubic-bezier(1, .3, .5, 1);
  -webkit-@{an}: anim;
  -webkit-@{ad}: .5s;
  -webkit-@{adi}: alternate;
  -webkit-@{adu}: .5s;                                 
  -webkit-@{afm}: forwards;
  -webkit-@{atf}: ease / cubi-bezier(1, .3, .5, 1);
 }
```

 ### Equivalently:

```css
 selector{
   background-color: red;
   float: left;
   transform: rotate(45deg) animate-name: anim;
   animate-delay: .5s;
   animate-direction: alternate;
   animate-duration: .5ms;
   animate-fill-mode: forwards;
   animate-timing-function: ease / cubic-bezier(1, .3, .5, 1) -webkit-animate-name: anim;
   -webkit-animate-delay: .5s;
   -webkit-animate-direction: alternate;
   -webkit-animate-duration: .5s;
   -webkit-animate-fill-mode: forwards;
   -webkit-animate-function: ease / cubic-bezier(1, .3, .5, 1);
 }
```
 > If you use sass, you will use '$' instead '@' to declaration the variable.
 > And recommend that all of the value of the variable should add single quotes or double quotes.
 > Then you can usse the variables above like this:
```sass
 selector{
          #{$bc}: red;
          #{$f}: left;
          #{$ts}: rotate(45deg)
          #{$an}: anim;
          #{$ad}: .5s;
          #{$adi}: alternate;
          #{$adu}: .5s;
          #{$afm}: forwards;
          #{$atf}: ease / cubic-bezier(1, .3, .5, 1);
  -webkit-#{$an}: anim;
  -webkit-#{$ad}: .5s;
  -webkit-#{$adi}: alternate;
  -webkit-#{$adu}: .5s;
  -webkit-#{$afm}: forwards;
  -webkit-#{$atf}: ease / cubi-bezier(1, .3, .5, 1);
 }

```
### Equivalently:
```css
 selector{
          background-color: red;
          float: left;
          transform: rotate(45deg)
          animate-name: anim;
          animate-delay: .5s;
          animate-direction: alternate;
          animate-duration: .5s;
          animate-fill-mode: forwards;
          animate-timing-function: ease / cubic-bezier(1, .3, .5, 1)
  -webkit-animate-name: anim;
  -webkit-animate-delay: .5s;
  -webkit-animate-direction: alternate;
  -webkit-animate-duration: .5s;
  -webkit-animate-fill-mode: forwards;
  -webkit-animate-function: ease / cubic-bezier(1, .3, .5, 1);
 }
```
